# Generated by Django 4.1 on 2022-08-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_useruploadmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadmodel',
            name='file',
            field=models.FileField(upload_to='file_uploads/%Y%m%d'),
        ),
    ]
