# Generated by Django 4.1 on 2022-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_useruploadmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadmodel',
            name='file',
            field=models.FileField(upload_to='file_uploads/%d%m%Y'),
        ),
    ]
